export const IpcChannels = {
  appInfo: 'cozypad:app:info',
  listProfiles: 'cozypad:profiles:list',
  saveProfile: 'cozypad:profiles:save',
  deleteProfile: 'cozypad:profiles:delete',
  connect: 'cozypad:connection:connect',
  disconnect: 'cozypad:connection:disconnect',
  connectionState: 'cozypad:connection:state',
  terminalOpen: 'cozypad:terminal:open',
  terminalWrite: 'cozypad:terminal:write',
  terminalResize: 'cozypad:terminal:resize',
  terminalClose: 'cozypad:terminal:close',
  terminalOutput: 'cozypad:terminal:output',
  terminalClosed: 'cozypad:terminal:closed',
  telemetryUpdated: 'cozypad:telemetry:updated',
  fsList: 'cozypad:fs:list',
  fsRead: 'cozypad:fs:read',
  fsReadBytes: 'cozypad:fs:read-bytes',
  fsWrite: 'cozypad:fs:write',
  fsCreate: 'cozypad:fs:create',
  fsRename: 'cozypad:fs:rename',
  fsDuplicate: 'cozypad:fs:duplicate',
  fsCopy: 'cozypad:fs:copy',
  fsMove: 'cozypad:fs:move',
  fsDelete: 'cozypad:fs:delete',
  hostKeyPrompt: 'cozypad:hostkey:prompt',
  hostKeyDecision: 'cozypad:hostkey:decision',
  remoteSettingsGet: 'cozypad:remote-settings:get',
  remoteSettingsSet: 'cozypad:remote-settings:set',
  tmuxStatus: 'cozypad:tmux:status',
  tmuxStatusChanged: 'cozypad:tmux:status-changed',
  tmuxInstall: 'cozypad:tmux:install',
  remoteCleanup: 'cozypad:remote:cleanup',
  tmuxInstallProgress: 'cozypad:tmux:install-progress',
  tmuxInstallLog: 'cozypad:tmux:install-log',
  tmuxSessionsChanged: 'cozypad:tmux:sessions-changed',
  clipboardRead: 'cozypad:clipboard:read',
  clipboardWrite: 'cozypad:clipboard:write',
} as const;

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels];
