import type {
  AgentKind,
  AgentSessionSummary,
  ChatItem,
  SlashCommand,
} from '@cozypad/contracts';

/** Agents workspace 的 UI 開發 fixtures；正式 adapter（Phase 2+）落地後由真實事件取代。 */

export const mockAgentSessions: AgentSessionSummary[] = [
  {
    id: 'claude-s1',
    agentKind: 'claude',
    title: '修 GPU 利用率偏低問題',
    host: 'gpu-box',
    project: 'seg-train',
    cwd: '~/projects/seg-train',
    status: 'waiting_approval',
    unread: 2,
    updatedAt: '2026-07-29T14:21:00+08:00',
  },
  {
    id: 'claude-s2',
    agentKind: 'claude',
    title: '重構 dataloader pipeline',
    host: 'gpu-box',
    project: 'seg-train',
    cwd: '~/projects/seg-train',
    status: 'running',
    unread: 0,
    updatedAt: '2026-07-29T13:02:00+08:00',
  },
  {
    id: 'claude-s3',
    agentKind: 'claude',
    title: '寫實驗結果摘要',
    host: 'lab-nas',
    project: 'paper-2026',
    cwd: '~/paper-2026',
    status: 'exited',
    unread: 0,
    updatedAt: '2026-07-28T22:40:00+08:00',
  },
  {
    id: 'codex-s1',
    agentKind: 'codex',
    title: '加上 metrics JSONL 輸出',
    host: 'gpu-box',
    project: 'seg-train',
    cwd: '~/projects/seg-train',
    status: 'ready',
    unread: 0,
    updatedAt: '2026-07-29T11:48:00+08:00',
  },
];

export const mockAgentTimelines: Record<string, ChatItem[]> = {
  'claude-s1': [
    {
      kind: 'message',
      id: 'c1-1',
      role: 'user',
      text: '訓練跑起來了但 GPU 利用率只有 35%，幫我看一下瓶頸在哪',
      timestamp: '2026-07-29T14:12:00+08:00',
    },
    {
      kind: 'message',
      id: 'c1-2',
      role: 'assistant',
      text: '我先看 GPU 目前的狀態和 dataloader 設定。',
      timestamp: '2026-07-29T14:12:10+08:00',
    },
    {
      kind: 'tool_call',
      id: 'c1-3',
      name: 'Bash',
      summary: 'nvidia-smi --query-gpu=utilization.gpu,memory.used --format=csv',
      status: 'completed',
      output:
        'utilization.gpu [%], memory.used [MiB]\n36 %, 18432 MiB\n34 %, 18201 MiB',
      durationMs: 420,
      timestamp: '2026-07-29T14:12:15+08:00',
    },
    {
      kind: 'tool_call',
      id: 'c1-4',
      name: 'Read',
      summary: 'train.py — dataloader 設定段落',
      status: 'completed',
      output: 'DataLoader(dataset, batch_size=32, num_workers=2, pin_memory=False)',
      durationMs: 180,
      timestamp: '2026-07-29T14:12:40+08:00',
    },
    {
      kind: 'message',
      id: 'c1-5',
      role: 'assistant',
      text: '瓶頸在資料端：`num_workers=2` 太低而且沒開 `pin_memory`，GPU 在等 CPU 餵資料。建議改成 workers=8 + pin_memory + persistent_workers，patch 如下。',
      timestamp: '2026-07-29T14:13:05+08:00',
    },
    {
      kind: 'file_diff',
      id: 'c1-6',
      path: 'train.py',
      additions: 4,
      deletions: 1,
      diff: [
        '@@ -41,7 +41,10 @@',
        ' loader = DataLoader(',
        '     dataset,',
        '     batch_size=32,',
        '-    num_workers=2,',
        '+    num_workers=8,',
        '+    pin_memory=True,',
        '+    persistent_workers=True,',
        '+    prefetch_factor=4,',
        ' )',
      ].join('\n'),
      timestamp: '2026-07-29T14:13:20+08:00',
    },
    {
      kind: 'approval',
      id: 'c1-7',
      command: 'python train.py --config configs/base.yaml --resume',
      cwd: '~/projects/seg-train',
      riskSummary: '重新啟動訓練 process；會覆蓋目前的 tmux pane 輸出',
      resolution: 'pending',
      timestamp: '2026-07-29T14:21:00+08:00',
    },
  ],
  'claude-s2': [
    {
      kind: 'message',
      id: 'c2-1',
      role: 'user',
      text: '把 dataset 前處理搬到獨立 worker，主程序只做 batch 組裝',
      timestamp: '2026-07-29T12:55:00+08:00',
    },
    {
      kind: 'message',
      id: 'c2-2',
      role: 'assistant',
      text: '好，我先盤點現有 pipeline 的耦合點再動手。',
      timestamp: '2026-07-29T12:55:12+08:00',
    },
    {
      kind: 'tool_call',
      id: 'c2-3',
      name: 'Grep',
      summary: 'preprocess( 的所有呼叫點',
      status: 'running',
      timestamp: '2026-07-29T13:02:00+08:00',
    },
    {
      kind: 'question',
      id: 'c2-4',
      prompt: '前處理 worker 要用哪種並行架構？這會影響 checkpoint 的相容性。',
      options: [
        { label: 'multiprocessing spawn', description: '隔離最乾淨，Windows/Linux 行為一致（推薦）' },
        { label: 'threads', description: '共享記憶體省 RAM，但受 GIL 限制' },
        { label: 'asyncio', description: '適合 IO-bound，前處理是 CPU-bound 不建議' },
      ],
      selectedIndex: null,
      timestamp: '2026-07-29T13:02:30+08:00',
    },
  ],
  'claude-s3': [
    {
      kind: 'message',
      id: 'c3-1',
      role: 'user',
      text: '幫我把 normalization ablation 的結果整理成一段摘要',
      timestamp: '2026-07-28T22:10:00+08:00',
    },
    {
      kind: 'message',
      id: 'c3-2',
      role: 'assistant',
      text: 'zscore 相對 baseline(none) 在 val/accuracy 提升 +2.3%（3 seeds, σ=0.4），minmax 只有 +0.8%。樣本數少，先當描述性結果，不下因果結論。',
      timestamp: '2026-07-28T22:12:30+08:00',
    },
    {
      kind: 'usage',
      id: 'c3-3',
      inputTokens: 18432,
      outputTokens: 2210,
      timestamp: '2026-07-28T22:12:31+08:00',
    },
  ],
  'codex-s1': [
    {
      kind: 'message',
      id: 'x1-1',
      role: 'user',
      text: '訓練 loop 每個 epoch 結束時把 metrics 寫成 JSONL，欄位照 CozyPad 的 contract',
      timestamp: '2026-07-29T11:40:00+08:00',
    },
    {
      kind: 'message',
      id: 'x1-2',
      role: 'assistant',
      text: '完成，寫入 `.cozypad/research/<run-id>/metrics.jsonl`，欄位含 name/value/step/split/timestamp。',
      timestamp: '2026-07-29T11:47:30+08:00',
    },
    {
      kind: 'file_diff',
      id: 'x1-3',
      path: 'src/metrics_writer.py',
      additions: 38,
      deletions: 0,
      diff: [
        '@@ -0,0 +1,38 @@',
        '+import json, os, datetime',
        '+',
        '+class MetricsWriter:',
        '+    def __init__(self, run_dir):',
        '+        self.path = os.path.join(run_dir, "metrics.jsonl")',
        '+    ...',
      ].join('\n'),
      timestamp: '2026-07-29T11:47:45+08:00',
    },
  ],
};

export const mockAgentInstallState: Record<AgentKind, 'installed' | 'not_detected'> = {
  claude: 'installed',
  codex: 'installed',
  agy: 'not_detected',
};

export const mockSlashCommands: Record<AgentKind, SlashCommand[]> = {
  claude: [
    { name: 'clear', description: '清空目前對話' },
    { name: 'compact', description: '壓縮歷史保留重點' },
    { name: 'help', description: '列出可用指令' },
    { name: 'model', description: '切換模型' },
    { name: 'resume', description: '接續既有 session' },
    { name: 'init', description: '初始化 CLAUDE.md' },
    { name: 'review', description: '審查目前變更' },
  ],
  codex: [
    { name: 'clear', description: '清空目前對話' },
    { name: 'diff', description: '顯示工作區變更' },
    { name: 'help', description: '列出可用指令' },
    { name: 'model', description: '切換模型' },
  ],
  agy: [{ name: 'help', description: '列出可用指令' }],
};
